### ISSUE TITLE
Provide GH release tarball asset with all submodules included

### ISSUE THREAD

**Issue by svmhdvn** [dzaima/CBQN#118]
I'd like to package CBQN for a couple of distributions, namely Alpine Linux and FreeBSD. In order to do so, it would be great if you could generate a release tarball with all git submodules included at a specific tag/commit of each (chosen by you). If you upload that as a Github asset in the "releases" section, then the release will stay "stable" on github (see https://github.blog/open-source/git/update-on-the-future-stability-of-source-code-archives-and-hashes/) and distributions can easily package it.

**Comment by dzaima** [comment]
Are full tarballs particularly necessary? After the xz debacle I'd have imagined there'd be less of a desire/a move away from what's effectively an arbitrary blob.

Also, in the case of CBQN, the question of whether to include or exclude the [precompiled bytecode](https://github.com/dzaima/cbqnBytecode/tree/c5674783c11d7569e5a4d166600ffcde2409331d/gen) is rather significant (a submodule of autogenerated code, not dissimilar from a binary blob encoded in C code, used by the default CBQN build to skip a bootstrapping step, but potentially undesirable to even have around for distributions wanting to build everything from source), which kind of complicates what even a "complete" tarball of CBQN would be.

**Comment by svmhdvn** [comment]
> Are full tarballs particularly necessary? After the xz debacle I'd have imagined there'd be less of a desire/a move away from what's effectively an arbitrary blob.

I agree, but distributions would ideally avoid using `git` to clone submodules at HEAD from VCS and instead either:
* have all versioned sources included in the tarball ready to build (so that the tarball's hash stays stable), OR
* pull each dependency as separate packages from the distro's repository, also each versioned and frozen

I'd like to build everything from source as that would ensure everything has a trail in the the software supply chain. Currently, it looks like mlochbaum/BQN isn't versioned so the bootstrapping instructions from the README (both option 1 and 2) won't work for packaging yet.

> Also, in the case of CBQN, the question of whether to include or exclude the [precompiled bytecode](https://github.com/dzaima/cbqnBytecode/tree/c5674783c11d7569e5a4d166600ffcde2409331d/gen) is rather significant

I would personally be on the side of *not* including the precompiled bytecode or any binary-like artifacts at all.

**Comment by dzaima** [comment]
CBQNs build system does allow for building from repo copies without going through git/submodules via `build/singeliLocal` / `build/replxxLocal` / `build/bytecodeLocal`; e.g. the NixOS package [has a frozen a revision/hash of all involved repos](https://github.com/NixOS/nixpkgs/blob/929b85a3a18a691256b43eb599126bd5b36191df/pkgs/development/interpreters/bqn/cbqn/sources.nix#L19-L57) and [copies them into CBQN](https://github.com/NixOS/nixpkgs/blob/929b85a3a18a691256b43eb599126bd5b36191df/pkgs/development/interpreters/bqn/cbqn/default.nix#L67-L80).

I hadn't thought about the fact that there isn't any direct reference of the desired mlochbaum/BQN version from CBQN directly, but the referenced bytecode submodule [does include within itself](https://github.com/dzaima/cbqnBytecode/blob/c5674783c11d7569e5a4d166600ffcde2409331d/info#L1) the specific used/desired mlochbaum/BQN revision (the CBQN revision is there because of the cyclic repo dependency (only there for strictly describing how it was built; using the target CBQN revision should always be fine/equivalent)). It'd make sense to reference it more directly in CBQNs tree somewhere, but including it as a submodule feels somewhat excessive. Perhaps just a similar `build/info.txt` file in CBQN?

While it makes sense to exclude the precompiled bytecode, it means that as-is the tarball still wouldn't build without pulling in more things manually anyway; for that to not be the case it'd need to contain a copy of mlochbaum/BQN (+ something for doing the bootstrapping (but still providing a choice between the methods?), and if such were to exist it'd be rather desirable for it to work from git clones too, which'd get extra messy with incremental compilation); and it'd be extra unnecessary stuff & work for those fine with precompiled bytecode. Providing a tarball for each option would make sense, but that means potential extra confusion.

Yeah all options are messy.. Ideally working with regular git copies would just be more widely feasible :/

**Comment by svmhdvn** [comment]
> CBQNs build system does allow for building from repo copies without going through git/submodules via `build/singeliLocal` / `build/replxxLocal` / `build/bytecodeLocal`; e.g. the NixOS package [has a frozen a revision/hash of all involved repos](https://github.com/NixOS/nixpkgs/blob/929b85a3a18a691256b43eb599126bd5b36191df/pkgs/development/interpreters/bqn/cbqn/sources.nix#L19-L57) and [copies them into CBQN](https://github.com/NixOS/nixpkgs/blob/929b85a3a18a691256b43eb599126bd5b36191df/pkgs/development/interpreters/bqn/cbqn/default.nix#L67-L80).

I like this approach and this should work for most distributions. For this to work deterministically across all distributions though, I think it would be better if you pin specific versions for all pulled-in dependencies/submodules for the tagged release of CBQN. You'd know which combinations of versions of all sources work best together (presumably, at least better than myself or other package/port contributors). Even if the versioning is arbitrary (i.e. HEAD of all submodules works fine), it's best to keep the commit hash or tagged version pinned.

> It'd make sense to reference it more directly in CBQNs tree somewhere, but including it as a submodule feels somewhat excessive. Perhaps just a similar `build/info.txt` file in CBQN?

I don't think that including it as a submodule is excessive. It would be clean and would consolidate dependencies into one place.

> While it makes sense to exclude the precompiled bytecode, it means that as-is the tarball still wouldn't build without pulling in more things manually anyway; for that to not be the case it'd need to contain a copy of mlochbaum/BQN (+ something for doing the bootstrapping (but still providing a choice between the methods?), and if such were to exist it'd be rather desirable for it to work from git clones too, which'd get extra messy with incremental compilation); and it'd be extra unnecessary stuff & work for those fine with precompiled bytecode. Providing a tarball for each option would make sense, but that means potential extra confusion.

Yes I agree and I see the issue. I think working with git submodules (as long as they're versioned as part of the tagged CBQN commit) should work fine.

**Comment by dzaima** [comment]
Submodule revisions are already pinned by git in every git commit; i.e. [here](https://github.com/dzaima/CBQN/tree/v0.7.0/build) you can see the specific hashes of 0.7.0; apparently e.g. `git ls-tree HEAD build/singeliSubmodule/` gives the hash from a git clone (no submodule initialization necessary)

**Comment by svmhdvn** [comment]
Thanks! Looks like everything should be easy enough to package with that then.

**Comment by svmhdvn** [comment]
Sorry to comment on this again. There's nothing further to change about the build process, but would it be possible for you to still provide a tarball of CBQN's sources, *excluding* all git submodules, in the Github releases page for each new tag? Essentially just what github generates through .tar.gz anyway on the tags page? This would allow maintainers to use the custom "watch" feature on Github to subscribe to notifications on new releases, and would maintain the following from my above comment:

> if you upload that as a Github asset in the "releases" section, then the release will stay "stable" on github (see https://github.blog/open-source/git/update-on-the-future-stability-of-source-code-archives-and-hashes/)

**Comment by dzaima** [comment]
The existing tarballs are already annoying as users may download them and find that they're entirely unusable; adding custom ones would make it seem even more like they're gonna be useful; to some extent some description in the release could help, but probably to a limited extent. I suppose if this were needed the best course of action would be to have both submodule-ful and submodule-less tarballs.

I assume that your use-case would require the Singeli and replxx repos to have tarballs matching CBQN versions too? Singeli would be somewhat weird in that CBQN just uses whatever revision happens to be necessary, which could end up in the weird situation where making a CBQN release would require making a Singeli release of a past commit.
