### ISSUE TITLE
Decoupling Singeli from CBQN build

### ISSUE THREAD

**Issue by yewscion** [dzaima/CBQN#46]
Would it be possible to decouple the singeli source from the source directory of an optimized CBQN build?

I'm specifically looking at https://github.com/dzaima/CBQN/blob/master/makefile#L216, where the Singeli source is pulled into the build directory. If someone were to have Singeli installed as a package, would it be possible to have a makefile variable to point to that instead of assuming the `Singeli` directory holds the entire build tree for Singeli?

I'm asking as this question was raised in the GNU Guix package update referenced in #45, which can be viewed [here](https://issues.guix.gnu.org/56575). As of right now, the source is included in the optimized build as a source that is grafted into the build directory. It would be more maintainable and user-friendly if we could simply package singeli separately and use that as a dependency of the optimized build, instead of duct taping the sources together as the package definition currently does.

Thoughts?

**Comment by dzaima** [comment]
Singeli, on its own, is a DSL code generator, implemented in BQN, invoked during compilation, outputting C to be fed into a C compiler; CBQNs makefile does all of that (including a bootstrap CBQN build to be able to run Singeli in the first place). Moving that process out of CBQN would be of severe harm to users compiling from source manually - in addition to needing to manually do the boostrapping step, they'd need to keep the Singeli version in sync with the one CBQN expects (which, if mismatched, can easily break, as the two largely are worked on in tandem, using new features & breaking old ones); a git submodule does this precisely, in the way that makes much sense given the relationship between CBQN and Singeli - Singeli just being an additional source code folder.

(the sources of mlochbaum/Singeli are used only at compile-time, i.e. the final CBQN binary includes everything it needs to run.)

That said, were Singeli to be its own package, it'd need to depend on a non-Singeli CBQN build, and the package itself would just be the mlochbaum/Singeli file tree; I suppose it would be possible to allow directly using an existing CBQN build & existing Singeli directory instead of CBQN building the bootstrap version & using the `ln -s`ed-in `Singeli/`, but I think that'd just end up more complicated.

**Comment by yewscion** [comment]
For the Guix package, we already have the non-Singeli bootstrap build, that can be used with the Singeli sources. And the non-optimized build we outlined in #45 is separate from that bootstrap version, as well.

If I'm understanding correctly, the installation process for Singeli as a package is currently expected to just be "copy the source tree into `$PATH`"? If so, I can easily define a package that does so, by wrapping the `singeli` script in another script that calls it inside of the expected directory, and then graft that entire directory during the optimized CBQN build. 

I was originally under the impressions that one could simply install the `singeli` script by copying it somewhere in `$PATH`, and that the entire directory was meant for development only. If that is the case, would it be possible to get a list of the minimum requirements for `singeli` in the build process of CBQN? I would like to avoid including any files that are not strictly necessary during the build, and to use the packaged version of `singeli` + any other needed sources from the repo.

Thank You for Your time!

**Comment by dzaima** [comment]
> If I'm understanding correctly, the installation process for Singeli as a package is currently expected to just be "copy the source tree into `$PATH`"?

There is no "installation process" for Singeli currently, CBQN is the only thing that uses it; were one to be made, it'd be just having [the singeli script](https://github.com/mlochbaum/Singeli/blob/master/singeli) into `$PATH` (and having all of the sources around it for it to use, i.e. all but `LICENSE`, `README.md`, and `test/`), and something for its `#! /usr/bin/env bqn` to find.

That latter part is quite problematic though, given that `bqn` is needed to be both the bootstrap build, and the final result build; options would be to either have a wrapper script that launches Singeli with the bootstrap CBQN interpreter, or temporarily switching what `/usr/bin/env bqn` is during the build process, or require explicitly invoking the script with the wanted CBQN interpreter.

Given that CBQNs `singeli=1` builds also need the bootstrap build for other purposes (see the `genArithTables` target), the last option is probably best, i.e. giving CBQNs `make` two new arguments - the path of the Singeli installation, and the location of a bootstrap CBQN build.

(replying here about another question in the guix discussion - an empty `PIE=` argument is perfectly acceptable to add for all targets; it'll result in a tiny bit less efficient code on x86-64 for scalar code, but that's not too much of a worry; at some point I'll get around to detecting for this in CBQNs makefile itself, but an unconditional position-independent build makes sense for a package anyway)
